# Site settings
title: Adam Ladachowski
description: Adam Ladachowski personal page
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Adam Ladachowski
user_description: Open-minded, communicative and resourceful Software Engineer with significant experience looking to secure an interesting and challenging role within the ranks of a solid organization. Professional solution delivery from design to implementation. Glad to prototype and test new approaches. Team leadership and project coordination experience available if required. Eager to learn and always willing to help.
user_title: Software Developer
email: adam.ladachowski@gmail.com
twitter_username: aladac
github_username:  aladac

exclude: ['package.json', 'src' , 'node_modules', 'yarn.lock', 'gulpfile.js', 'package-lock.json']

plugins:
  - jekyll-haml
